module.exports = [
  {
    name: "Ramesh Pawar",
    message: "Flooding in low-lying areas.",
    location: { lat: 18.5204, lng: 73.8567 },
    status: "critical",
    disasterType: "Flood",
    createdAt: new Date("2025-04-01"),
  },
  {
    name: "Priya Nair",
    message: "Strong earthquake tremors felt.",
    location: { lat: 28.7041, lng: 77.1025 },
    status: "pending",
    disasterType: "Earthquake",
    createdAt: new Date("2025-04-02"),
  },
  {
    name: "Arjun Mehta",
    message: "Wildfire spreading in forest area.",
    location: { lat: 34.0837, lng: 74.7973 },
    status: "critical",
    disasterType: "Wildfire",
    createdAt: new Date("2025-03-29"),
  },
  {
    name: "Sunita Reddy",
    message: "Landslide near hillside road.",
    location: { lat: 15.2993, lng: 74.124 },
    status: "resolved",
    disasterType: "Landslide",
    createdAt: new Date("2025-03-28"),
  },
  {
    name: "Mohammed Khan",
    message: "Cyclone warning issued.",
    location: { lat: 17.385, lng: 78.4867 },
    status: "pending",
    disasterType: "Cyclone",
    createdAt: new Date("2025-04-03"),
  },
  {
    name: "Deepa Joshi",
    message: "Severe heatwave affecting the region.",
    location: { lat: 19.076, lng: 72.8777 },
    status: "critical",
    disasterType: "Heatwave",
    createdAt: new Date("2025-03-25"),
  },
  {
    name: "Raj Malhotra",
    message: "Floodwaters entering residential area.",
    location: { lat: 22.5726, lng: 88.3639 },
    status: "resolved",
    disasterType: "Flood",
    createdAt: new Date("2025-04-01"),
  },
  {
    name: "Ayesha Shaikh",
    message: "Volcanic activity observed nearby.",
    location: { lat: 13.0827, lng: 80.2707 },
    status: "pending",
    disasterType: "Volcanic Eruption",
    createdAt: new Date("2025-03-31"),
  },
  {
    name: "Kunal Verma",
    message: "Tsunami alert after earthquake.",
    location: { lat: 9.9252, lng: 78.1198 },
    status: "critical",
    disasterType: "Tsunami",
    createdAt: new Date("2025-04-04"),
  },
  {
    name: "Ritika Sharma",
    message: "Thunderstorm damage reported.",
    location: { lat: 25.3176, lng: 82.9739 },
    status: "resolved",
    disasterType: "Thunderstorm",
    createdAt: new Date("2025-03-27"),
  },
  {
    name: "Sandeep Rao",
    message: "Drought conditions worsening in village.",
    location: { lat: 21.1702, lng: 72.8311 },
    status: "critical",
    disasterType: "Drought",
    createdAt: new Date("2025-03-23"),
  },
  {
    name: "Meena Iyer",
    message: "Cyclone damage to power lines.",
    location: { lat: 16.5062, lng: 80.648 },
    status: "resolved",
    disasterType: "Cyclone",
    createdAt: new Date("2025-03-30"),
  },
  {
    name: "Abhay Patil",
    message: "Earthquake cracks found in roads.",
    location: { lat: 18.5204, lng: 73.8567 },
    status: "pending",
    disasterType: "Earthquake",
    createdAt: new Date("2025-03-26"),
  },
  {
    name: "Neha Kulkarni",
    message: "Landslide blocks main highway.",
    location: { lat: 12.9716, lng: 77.5946 },
    status: "critical",
    disasterType: "Landslide",
    createdAt: new Date("2025-03-22"),
  },
  {
    name: "Vinod Yadav",
    message: "Forest fire approaching village edge.",
    location: { lat: 11.0168, lng: 76.9558 },
    status: "pending",
    disasterType: "Wildfire",
    createdAt: new Date("2025-03-21"),
  },
];
